/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sparse4s_GrBType */

#ifndef _Included_sparse4s_GrBType
#define _Included_sparse4s_GrBType
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sparse4s_GrBType
 * Method:    grbBoolean
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_sparse4s_GrBType_grbBoolean
  (JNIEnv *, jobject);

/*
 * Class:     sparse4s_GrBType
 * Method:    grbByte
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_sparse4s_GrBType_grbByte
  (JNIEnv *, jobject);

/*
 * Class:     sparse4s_GrBType
 * Method:    grbShort
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_sparse4s_GrBType_grbShort
  (JNIEnv *, jobject);

/*
 * Class:     sparse4s_GrBType
 * Method:    grbInt
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_sparse4s_GrBType_grbInt
  (JNIEnv *, jobject);

/*
 * Class:     sparse4s_GrBType
 * Method:    grbLong
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_sparse4s_GrBType_grbLong
  (JNIEnv *, jobject);

/*
 * Class:     sparse4s_GrBType
 * Method:    grbFloat
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_sparse4s_GrBType_grbFloat
  (JNIEnv *, jobject);

/*
 * Class:     sparse4s_GrBType
 * Method:    grbDouble
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_sparse4s_GrBType_grbDouble
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
