/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sparse4s_GrB */

#ifndef _Included_sparse4s_GrB
#define _Included_sparse4s_GrB
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sparse4s_GrB
 * Method:    init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_sparse4s_GrB_init
  (JNIEnv *, jobject);

/*
 * Class:     sparse4s_GrB
 * Method:    Finalize
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_sparse4s_GrB_Finalize
  (JNIEnv *, jobject);

/*
 * Class:     sparse4s_GrB
 * Method:    createMatrix
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_sparse4s_GrB_createMatrix
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     sparse4s_GrB
 * Method:    freeMatrix
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_sparse4s_GrB_freeMatrix
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
